- name: Find changed namespace dirs and tfvars
  id: find_dirs
  shell: bash
  run: |
    git fetch origin main
    changed_files=$(git diff --name-only origin/main HEAD | grep '^namespaces/' || true)
    if [[ -z "$changed_files" ]]; then
      echo "No namespaces changed."
      echo "dirs=[]" >> $GITHUB_OUTPUT
      exit 0
    fi
    
    echo "All changed files in namespaces:"
    echo "$changed_files"
    echo "---"
    
    # Filter files to only include dev.tfvars and prod.tfvars
    changed_tfvars=$(echo "$changed_files" | grep -E '/(dev|prod)\.tfvars$' || true)
    
    if [[ -z "$changed_tfvars" ]]; then
      echo "No dev.tfvars or prod.tfvars files changed."
      echo "dirs=[]" >> $GITHUB_OUTPUT
      exit 0
    fi
    
    echo "Changed tfvars files:"
    echo "$changed_tfvars"
    echo "---"
    
    # Extract unique namespace names from changed tfvars files
    changed_dirs=$(printf "%s\n" "$changed_tfvars" \
      | cut -d/ -f2 \
      | sort -u \
      | jq -R . | jq -s -c .)
    
    echo "Namespaces with changed tfvars: $changed_dirs"
    echo "dirs=$changed_dirs" >> $GITHUB_OUTPUT