name: Terraform Deploy (GitHub-hosted Runner)
on:
 push:
    branches:
     - gitwork
  
jobs:
 terraform:
  runs-on: ubuntu-latest

  outputs:
      dirs: ${{ steps.find_dirs.outputs.dirs }}
  env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
  steps:
    - name: checkout-code
      uses: actions/checkout@v4

    - name: Find changed namespace dirs
      id: find_dirs
      shell: bash
      run: |
        # 1. Fetch remote main
        git fetch origin main

        # 2. Get changed files under namespaces/, or empty
        changed_files=$(git diff --name-only origin/main HEAD \
          | grep '^namespaces/' || true)

        # 3. Bail if none
        if [[ -z "$changed_files" ]]; then
          echo "No namespaces changed."
          echo "dirs=[]" >> $GITHUB_OUTPUT
          exit 0
        fi

        # 4. Compute unique directory names
        changed_dirs=$(printf "%s\n" "$changed_files" \
          | xargs -n1 dirname \
          | sort -u \
          | jq -R . | jq -s -c .)

        # Print for human readability
        echo "Changed namespace directories: $changed_dirs"

        # Export for use as a matrix or later steps
        echo "dirs=$changed_dirs" >> $GITHUB_OUTPUT

 depploy:
   needs: terraform
   runs-on: ubuntu-latest
   strategy:
      matrix:
        dir: ${{ fromJson(needs.terraform.outputs.dirs) }}
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
          fetch-depth: 0

     - name: Terraform in ${{ matrix.dir }}
       uses: ./.github/workflows/terraform-deploy.yaml
       with:
        dir: ${{ matrix.dir }}


