name: Terraform Deploy (GitHub-hosted Runner)
on:
 push:
    branches:
     - main
  
jobs:
 terraform:
  name: Terraform-Deploy
  runs-on: self-hosted

#   defaults:
#       run:
#         working-directory: terraform-projects 

#   env: 
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: us-east-1
  steps:
    - name: checkout-code
      uses: actions/checkout@v4

    - name: find dir
      run: |
         ls
         echo " i am using the self hosted runners "
       
  